# -------------------------------------------------------------------------------- #
# Description                                                                      #
# -------------------------------------------------------------------------------- #
# This is the release pipeline and should contain all the tasks that need to run   #
# as part of a release.                                                            #
#                                                                                  #
# Trigger Rules:                                                                   #
#    push: master or main and only when a tag is set.                              #
#                                                                                  #
# Runs From:                                                                       #
#    Runs from the latest tag.                                                     #
# -------------------------------------------------------------------------------- #
name: release
on:
  push:
    tags: 
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: get_tag
        uses: dawidd6/action-get-tag@v1
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_tag.outputs.tag }}
