name: 'Versions'
description: 'Get Versions'

outputs:
  alpine-versions:
    description: "Alpine Versions"
    value: ${{steps.alpine.outputs.versions}}
  centos-versions:
    description: "Centos Versions"
    value: ${{steps.centos.outputs.versions}}
  debian-versions:
    description: "Debian Versions"
    value: ${{steps.debian.outputs.versions}}

runs:
  using: "composite"
  steps:
#    - uses: actions/checkout@v2
    - id: alpine
      run: echo "::set-output name=versions::$(ls Dockerfiles/alpine|sort -n|jq -cnR '[inputs | select(length>0)]')"
      shell: bash
    - id: centos
      run: echo "::set-output name=versions::$(ls Dockerfiles/centos|sort -n|jq -cnR '[inputs | select(length>0)]')"
      shell: bash
    - id: debian
      run: echo "::set-output name=versions::$(ls Dockerfiles/debian|sort -n|jq -cnR '[inputs | select(length>0)]')"
      shell: bash
