# -------------------------------------------------------------------------------- #
# Description                                                                      #
# -------------------------------------------------------------------------------- #
# This is the ci (continuous integration) pipeline and should contain all the      #
# tasks that need to be run whenever a push is made.                               #
#                                                                                  #
# Trigger Rules:                                                                   #
#    push: all branches, excluding all tags and *.md files.                        #
#    pull requests: master/main (target only), exclude *.md files.                 #
#                                                                                  #
# Runs From:                                                                       #
#    Runs from the latest commit.                                                  #
# -------------------------------------------------------------------------------- #

name: ci
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - $default-branch
    paths-ignore:
      - '**/*.md'
    
jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Shellcheck
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/shellcheck/master/pipeline.sh)
  slack-workflow-status:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Slack Post Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          include_jobs: true
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
