name: CICD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  SLACK_NOTIFY: true

permissions: read-all

jobs:
  set-output-defaults:
    name: Set Output Defaults
    runs-on: ubuntu-latest
    outputs:
      slack-notify: ${{ steps.set-output-defaults.outputs.slack-notify }}
    steps:
      - name: set outputs with default values
        id: set-output-defaults
        run: |
          echo "slack-notify=${{ env.SLACK_NOTIFY }}" >> "${GITHUB_OUTPUT}"

  shellcheck:
    name: ShellCheck (Local)
    uses: actionstoolbox/reusable-workflows/.github/workflows/reusable-shellcheck.yml@master

  slack-workflow-status:
    if: always()
    name: Slack (Local)
    needs:
      - set-output-defaults
      - shellcheck
    uses: actionstoolbox/reusable-workflows/.github/workflows/reusable-slack.yml@master
    with:
      slack_notify: ${{ needs.set-output-defaults.outputs.slack-notify }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
