# -------------------------------------------------------------------------------- #
# Description                                                                      #
# -------------------------------------------------------------------------------- #
# This is the release pipeline and should contain all the taks that need to be run #
# as part of a release.                                                            #
#                                                                                  #
# Trigger Rules:                                                                   #
#    push: master or main and only when a tag is set.                              #
#                                                                                  #
# Runs From:                                                                       #
#    Runs from the latest tag.                                                     #
# -------------------------------------------------------------------------------- #
name: cron
on: 
  schedule:
  - cron: '*/5 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Release
        id: get_current_release
        uses: joutvhu/get-release@v1
        with:
          latest: true
#      - name: Get the current tag
#        id: get_tag
#        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_current_release.outputs.tag_name }}
