# -------------------------------------------------------------------------------- #
# Description                                                                      #
# -------------------------------------------------------------------------------- #
# This is the release pipeline and should contain all the tasks that need to run   #
# as part of a release.                                                            #
#                                                                                  #
# Trigger Rules:                                                                   #
#    push: master or main and only when a tag is set.                              #
#                                                                                  #
# Runs From:                                                                       #
#    Runs from the latest tag.                                                     #
# -------------------------------------------------------------------------------- #
name: cron
on: 
  schedule:
  - cron: '*/5 * * * *'

env:
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Release
        id: get_current_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_current_release.outputs.release }}
