name: Delete old workflow runs

on:
  workflow_dispatch:
    inputs:
      older-than-seconds:
        description: 'Number of seconds'
        required: true
        default: '604800'
      slack-notify:
        description: 'Notify Slack'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

  schedule:
    - cron: '30 4 * * *'

env:
  SLACK_NOTIFY: false
  OLDER_THANK_SECONDS: 604800

# Declare default permissions as read only.
permissions: read-all

jobs:
  set-output-defaults:
    name: Set Output Defaults
    runs-on: ubuntu-latest
    outputs:
      slack-notify: ${{ steps.set-output-defaults.outputs.slack-notify }}
      older-than-seconds: ${{ steps.set-output-defaults.outputs.older-than-seconds }}
    steps:
      - name: set outputs with default values
        id: set-output-defaults
        run: |
          echo "slack-notify=${{ github.event.inputs.slack-notify || env.SLACK_NOTIFY }}" >> "${GITHUB_OUTPUT}"
          echo "older-than-seconds=${{ github.event.inputs.older-than-seconds || env.OLDER_THAN_SECONDS }}" >> "${GITHUB_OUTPUT}"

  delete-old-workflows:
    name: Delete old workflow runs (Local)
    permissions:
      actions: write
    needs:
      - set-output-defaults
    uses: WolfSoftware/reusable-workflows/.github/workflows/reusable-delete-old-runs.yml@master
    with:
      older-than-seconds: ${{ needs.set-output-defaults.outputs.older-than-seconds }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  slack-workflow-status:
    if: always()
    name: Slack (Local)
    needs:
      - set-output-defaults
      - delete-old-workflows
    uses: WolfSoftware/reusable-workflows/.github/workflows/reusable-slack.yml@master
    with:
      slack_notify: ${{ needs.set-output-defaults.outputs.slack-notify }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
