name: dynamic3
on: 
  push:

jobs:
  create-matrices:
    name: Create version matrices
    runs-on: ubuntu-latest
    outputs:
      alpine-versions: ${{steps.alpine.outputs.versions}}
      centos-versions: ${{steps.centos.outputs.versions}}
      debian-versions: ${{steps.debian.outputs.versions}}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Generate alpine version matrix
        id: alpine
        run: echo "::set-output name=versions::$(ls Dockerfiles/alpine|sort -n|jq -cnR '[inputs | select(length>0)]')"
      - name: Generate centos version matrix
        id: centos
        run: echo "::set-output name=versions::$(ls Dockerfiles/centos|sort -n|jq -cnR '[inputs | select(length>0)]')"
      - name: Generate debian version matrix
        id: debian
        run: echo "::set-output name=versions::$(ls Dockerfiles/debian|sort -n|jq -cnR '[inputs | select(length>0)]')"
  alpine:
    runs-on: ubuntu-latest
    needs: create-matrices
    strategy:
      fail-fast: false
      matrix:
        version: ${{fromJson(needs.create-matrices.outputs.alpine-versions)}}
    name: Test on Alpine Linux ${{ matrix.version }}
    steps:
      - run: echo ${{ matrix.version }}
  centos:
    runs-on: ubuntu-latest
    needs: create-matrices
    strategy:
      fail-fast: false
      matrix:
        version: ${{fromJson(needs.create-matrices.outputs.centos-versions)}}
    name: Test on Centos ${{ matrix.version }}
    steps:
      - name: Test on Centos ${{ matrix.version }}
        run: echo ${{ matrix.version }}
  debian:
    runs-on: ubuntu-latest
    needs: create-matrices
    strategy:
      fail-fast: false
      matrix:
        version: ${{fromJson(needs.create-matrices.outputs.debian-versions)}}
    name: Test on Debian ${{ matrix.version }}
    steps:
      - name: Test on Debian ${{ matrix.version }}
        run: echo ${{ matrix.version }}
  slack:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - alpine
      - centos
      - debian
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Slack Workflow Notifications
        uses: come25136/workflow-notification-for-slack@1.0.0
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          include_jobs: on-failure
