name: dynamic
on: 
  push:

jobs:
  create-matrices:
    runs-on: ubuntu-latest
    outputs:
      alpine-versions: ${{steps.alpine.outputs.matrix}}
      debian-versions: ${{steps.debian.outputs.matrix}}
    steps:
      - uses: actions/checkout@v2
      - id: alpine
        run: echo "::set-output name=alpine-versions::$(ls Dockerfiles/alpine|sort -n|jq -cnR '[inputs | select(length>0)]')"
      - id: debian
        run: echo "::set-output name=debian-versions::$(ls Dockerfiles/debian|sort -n|jq -cnR '[inputs | select(length>0)]')"


  alpine:
    runs-on: ubuntu-latest
    needs: create-matrices
    strategy:
      matrix:
        version: ${{fromJson(needs.create-matrices.outputs.alpine-versions)}}
    steps:
      - run: echo ${{ matrix.version }}
  debian:
    runs-on: ubuntu-latest
    needs: create-matrices
    strategy:
      version:
        subdir: ${{fromJson(needs.create-matrices.outputs.debian-versions)}}
    steps:
      - run: echo ${{ matrix.version }}
