name: Jobs
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2
    - id: foo
      uses: ./.github/workflows/composite/random-number
    - run: echo random-number ${{ steps.foo.outputs.random-number }} 
      shell: bash
