name: release
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - id: foo
      uses: user/composite@v1
    - run: echo random-number ${{ steps.foo.outputs.random-number }} 
      shell: bash
