# -------------------------------------------------------------------------------- #
# Description                                                                      #
# -------------------------------------------------------------------------------- #
# This is the release pipeline and should contain all the taks that need to be run #
# as part of a release.                                                            #
#                                                                                  #
# Trigger Rules:                                                                   #
#    push: master or main and only when a tag is set.                              #
#                                                                                  #
# Runs From:                                                                       #
#    Runs from the latest tag.                                                     #
# -------------------------------------------------------------------------------- #

$default-branch

name: release
on:
  push:
    tags: 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Exit if not on master branch
        if: endsWith(github.ref, $default-branch) == false
        run: exit -1
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_tag_name.outputs.VERSION }}
