name: Create Release Notes

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get current version
        id: get-current-version
        run: |
          RELEASE_VERSION="${GITHUB_REF#refs/*/}"
          echo "::set-output name=version::${RELEASE_VERSION}"

      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
#          name: Release ${{ steps.get-current-version.outputs.version }}
          name: Release ${{ github.ref }}
          body: ${{ steps.Changelog.outputs.changelog }}
#          generate_release_notes: true
          draft: false
          prerelease: false
