# -------------------------------------------------------------------------------- #
# Description                                                                      #
# -------------------------------------------------------------------------------- #
# This is the release pipeline and should contain all the taks that need to be run #
# as part of a release.                                                            #
#                                                                                  #
# Trigger Rules:                                                                   #
#    push: master or main and only when a tag is set.                              #
#                                                                                  #
# Runs From:                                                                       #
#    Runs from the latest tag.                                                     #
# -------------------------------------------------------------------------------- #
name: release
on:
  push:
    tags: 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v5
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.branch-name.outputs.tag }}
      - name: Echo default branch
        run: echo "${{ steps.branch-name.outputs.current_branch }}"
      - name: Echo default branch status
        run: "echo ${{ steps.branch-name.outputs.is_default }}"
      - name: Check default branch
        if: steps.branch-name.outputs.is_default != 'true'
        uses: actions/github-script@v3
        with:
          script: core.setFailed('Tag not on default branch')

#jobs:
#  test:
#    if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
#    runs-on: ubuntu-latest
#    steps:
#      - name: Get tag name
#        id: get_tag_name
#        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
#      - uses: actions/checkout@v2
#        with:
#          ref: ${{ steps.get_tag_name.outputs.VERSION }}
#      - name: Get branch name
#        id: branch-name
#        uses: tj-actions/branch-names@v5
#        if: steps.branch-name.outputs.is_default == 'true'
#      - name: 1
#        shell: bash
#        run: echo "${{ github.event.repository.default_branch }}"
#      - name: 2
#        shell: bash
##        run: echo "${GITHUB_REF##*/}"
#      - name: 3
#        shell: bash
#        run: echo "${{ format('refs/heads/{0}', github.event.repository.default_branch) }}"


