name: reusable
on:
  push:

jobs:
  build-alpine:
    name: Alpine Linux
    uses: actionstoolbox/container-framework-actions/.github/workflows/build-containers.yml@master
    with:
      directory: alpine
      os-name: Alpine Linux
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}
      slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
  build-centos:
    name: Centos
    uses: actionstoolbox/container-framework-actions/.github/workflows/build-containers.yml@master
    with:
      directory: centos
      os-name: Centos
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}
      slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
  build-debian:
    name: Debian
    uses: actionstoolbox/container-framework-actions/.github/workflows/build-containers.yml@master
    with:
      directory: debian
      os-name: Debian
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}
      slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
