name: reusable
on:
  push:

jobs:
  build-alpine:
    name: Alpine Linux
    uses: actionstoolbox/container-framework-actions/.github/workflows/build-containers.yml@master
    with:
      directory: alpine
      os-name: Alpine Linux
  build-centos:
    name: Centos
    uses: actionstoolbox/container-framework-actions/.github/workflows/build-containers.yml@master
    with:
      directory: centos
      os-name: centos
  slack-workflow-status:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - build-alpine
      - build-centos
      - debian
      - oraclelinux
      - photon
      - scientificlinux
      - ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Slack Post Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          include_jobs: true
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
