name: reusable
on:
  push:

jobs:
  alpine:
    name: Alpine Linux
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: alpine
      os-name: Alpine Linux
  centos:
    name: Centos
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: centos
      os-name: Centos
  debian:
    name: Debian
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: debian
      os-name: Debian
      publish: true
  slack-workflow-status:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - alpine
      - centos
      - debian
    runs-on: ubuntu-latest
    steps:
      - name: Slack Post Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          include_jobs: true
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
