name: reusable

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  get-git-ref:
    name: Get Git Ref
    runs-on: ubuntu-latest
    outputs:
      ref: ${{steps.get-git-ref.outputs.ref}}
    steps:
      - name: Checkout Repo
        run: echo "::set-output name=ref::${{ github.ref }}"
  alpine:
    needs: get-git-ref
    name: Alpine Linux
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: alpine
      lint: false
      ref: ${{ needs.get-git-ref.outputs.ref }}
  centos:
    needs: get-git-ref
    name: Centos
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: centos
      publish_dh: true
      ref: ${{ needs.get-git-ref.outputs.ref }}
  debian:
    needs: get-git-ref
    name: Debian
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: debian
      publish_gh: true
      ref: ${{ needs.get-git-ref.outputs.ref }}
  photon:
    needs: get-git-ref
    name: Photon
    uses: actionstoolbox/container-framework-actions/.github/workflows/multiple-os-workflow.yml@master
    with:
      directory: photon
      ref: ${{ needs.get-git-ref.outputs.ref }}
  slack-workflow-status:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - alpine
      - debian
      - photon
    runs-on: ubuntu-latest
    steps:
      - name: Slack Post Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          include_jobs: true
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
