name: reusable
on:
  push:

jobs:
  alpine:
    name: Alpine Linux
    runs-on: ubuntu-latest
    uses: actionstoolbox/container-framework-actions/workflows/test@master
    with:
      directory: 'alpine'
      os-name: 'Alpine Linux'



